version: '2'
services:
  rails:
    build: .
    image: app1-rails
    volumes:
      - ./:/app
    environment:
      - RAILS_LOG_TO_STDOUT=1
    depends_on:
      - db

  nginx:
    build: containers/nginx
    image: app1-nginx
    ports:
      - "80:80"

  db:
    image: postgres
